### ISSUE TITLE
Ambient light does not work without point lights

### ISSUE THREAD

**Issue by Sapein** [jgayfer/bevy_light_2d#16]
Not entirely certain if this is an issue with this crate, or with one of the other two crates I've minimized this issue to, however either way it's a regression.

This also seems to affect bevy_ecs_tilemap

Here's a repository that has the minimal setup: https://github.com/Sapein/bevy_light_2d_issue

However with the right versions the following works:
```Rust
use bevy::prelude::*;
use bevy_ecs_ldtk::prelude::*;
use bevy_light_2d::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins.set(ImagePlugin::default_nearest()))
        .add_plugins(LdtkPlugin)
        .add_plugins(Light2dPlugin)
        .add_systems(Startup, spawn_camera)
        .add_systems(Startup, spawn_ldtk_world)
        .insert_resource(LevelSelection::index(0))
        .run();
}
fn spawn_ldtk_world(mut command: Commands, asset_server: Res<AssetServer>, mut level_plugin: ResMut<LdtkSettings>) {
    // level_plugin.level_spawn_behavior = LevelSpawnBehavior::UseZeroTranslation;
    level_plugin.level_spawn_behavior = LevelSpawnBehavior::UseWorldTranslation { load_level_neighbors: true };
    command.spawn((LdtkWorldBundle {
        ldtk_handle: asset_server.load("tbg.ldtk"),
        ..Default::default()
    }, Name::new("World")));
}

fn spawn_camera(mut command: Commands) {
    command.spawn((Camera2dBundle::default(), AmbientLight2d {
        brightness: 0.1,
        ..default()
    }));
}
```

The issue is that the brightness isn't being applied as it should be.

**Comment by jgayfer** [comment]
On [Discord](https://discord.com/channels/691052431525675048/1258641023228182529/1258914300068761741) we were suspicious that this might be isolated to `bevy_ecs_tilemap`.

I tried adding in `bevy_ecs_tilemap` usage to the [dungeon example](https://github.com/jgayfer/bevy_light_2d/tree/bevy_ecs_tilemap-test), but it seems to work fine (my silly repeating background aside).

**Comment by Sapein** [comment]
Turns out the issue is with this crate entirely. AmbientLight2d does not work without PointLight2d. This can be demonstrated by disabling the `spawn_candles` system in the dungeon example and running the example twice, with two different AmbientLight2d values. They will look the same. However, if you run the examples twice, with `spawn_candles` system being enabled, then it will work and they will look different. 

This has nothing to do with bevy_ecs_ldtk or bevy_ecs_tilemap it seems.

**Comment by jgayfer** [comment]
Yep! Ambient light doesn't work if there aren't any point lights. Thanks for helping me track this down.

**Comment by Sapein** [comment]
My pleasure! I actually *really* like this crate, so glad I could help, apologies for being a bit wrong on the cause though.

**Comment by jgayfer** [comment]
No worries! I'm glad you like it. I was worried the initial release was too limited in scope, but it seems to have resonated with a lot of people.

I'm not immediately sure what the fix is here, but I'll get something sorted hopefully soon. I think I'm just misusing `GpuArrayBuffer`.

**Comment by Sapein** [comment]
It happened to fit the exact need that I needed, and when I was looking into it. Plus it's very easy to use, which is very nice. Other crates may have more features, but I don't really need all of that and they can be a bit...complex with multiple cameras and everything else.

**Comment by jgayfer** [comment]
It looks like we're [returning early in our `LightingNode`](https://github.com/jgayfer/bevy_light_2d/blob/c06faedeb3d982e5fae5a4217ecabe25b99b3249/src/render/lighting/node.rs#L61-L66) when the `GpuArrayBuffer` of extracted point light is empty, causing the lighting pass not to run.

Have a busy week ahead of me so likely won't be able to poke this more for a bit, but was able to at least identify where the issue is coming from. I'm not 100% sure yet how to handle empty array bindings.
