### ISSUE TITLE
Lights not visible when ambient light is 0 brightness

### ISSUE THREAD

**Issue by aMyTimed** [jgayfer/bevy_light_2d#22]
with a This:
```rust
    AmbientLight2d {
        brightness: 0.01,
        ..default()
    },
```
i can just barely see my lights which are like:
```rust
    entity.insert(PointLight2d {
        color: Color::srgba_u8(color.r, color.g, color.b, color.a),
        radius: 20.0,
        intensity: 15.0,
        falloff: 4.0,
        cast_shadows: true,
    });
```
![image](https://github.com/user-attachments/assets/3eae6615-fe29-4dc6-943e-3e3ca3c49c22)

---

when brightness is 1, lights fully visible

![image](https://github.com/user-attachments/assets/ebf73118-1785-422c-aa78-284b372facd7)

then when i set brightness of ambient light to 0, i cant see any of my lights anymore

![image](https://github.com/user-attachments/assets/ef894ada-8a52-4ecf-a625-540237a7ca63)

**Comment by jgayfer** [comment]
Thanks for the report. Looks like ambient light might be being multiplied against point lights. Will take a look.

**Comment by isidornygren** [comment]
I had a similar issue and opened up a PR that fixed it when I tested it locally: https://github.com/jgayfer/bevy_light_2d/pull/24
