### ISSUE TITLE
Blind spot at bottom of pointlights

### ISSUE THREAD

**Issue by aMyTimed** [jgayfer/bevy_light_2d#23]
When I'm moving my camera around, if I position it at certain spots this cone gap will appear at the bottom:

![image](https://github.com/user-attachments/assets/2f7052e3-1ea6-4f96-ad79-6b2edee849a4)

![image](https://github.com/user-attachments/assets/2cc30b86-3af0-4499-8405-e0efd7ce6711)

![image](https://github.com/user-attachments/assets/233cf430-5b9c-44bf-b36d-baf9e620b37f)

It disappears when my camera isn't in such positions:

![image](https://github.com/user-attachments/assets/83164242-85f7-4e83-9cb1-b8cc674e0fdd)

may be tricky to reproduce, I have many lights in my game and only one did this, it was at (0, 3)

**Comment by jgayfer** [comment]
Thanks for the report! I have a hunch as to what this is. Will report back my findings.

**Comment by jgayfer** [comment]
For more context, this happens as we add an "empty" occluder during our extraction step to get around the fact that `GpuArrayBuffer` won't write to the GPU with an empty list.

We might need a shader def to handle when the array is empty? I'm not certain if there's a bug in Bevy or not, as it does strike me as jarring that no binding is created with an empty array. I'll follow up on the Bevy Discord.

**Comment by jgayfer** [comment]
@aMyTimed Put up a [PR](#27 ) that I _believe_ fixes this. Wouldn't mind a look, if you're able!
